# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from mtp_plugin_kubernetes.models.base_model_ import Model
from mtp_plugin_kubernetes.models.create_compute_resource_reservation_request_compute_pool_reservation_compute_attributes import CreateComputeResourceReservationRequestComputePoolReservationComputeAttributes  # noqa: F401,E501
from mtp_plugin_kubernetes import util


class CreateComputeResourceReservationRequestComputePoolReservation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, compute_attributes: CreateComputeResourceReservationRequestComputePoolReservationComputeAttributes=None, num_cpu_cores: int=None, num_vc_instances: int=None, virtual_mem_size: float=None):  # noqa: E501
        """CreateComputeResourceReservationRequestComputePoolReservation - a model defined in Swagger

        :param compute_attributes: The compute_attributes of this CreateComputeResourceReservationRequestComputePoolReservation.  # noqa: E501
        :type compute_attributes: CreateComputeResourceReservationRequestComputePoolReservationComputeAttributes
        :param num_cpu_cores: The num_cpu_cores of this CreateComputeResourceReservationRequestComputePoolReservation.  # noqa: E501
        :type num_cpu_cores: int
        :param num_vc_instances: The num_vc_instances of this CreateComputeResourceReservationRequestComputePoolReservation.  # noqa: E501
        :type num_vc_instances: int
        :param virtual_mem_size: The virtual_mem_size of this CreateComputeResourceReservationRequestComputePoolReservation.  # noqa: E501
        :type virtual_mem_size: float
        """
        self.swagger_types = {
            'compute_attributes': CreateComputeResourceReservationRequestComputePoolReservationComputeAttributes,
            'num_cpu_cores': int,
            'num_vc_instances': int,
            'virtual_mem_size': float
        }

        self.attribute_map = {
            'compute_attributes': 'computeAttributes',
            'num_cpu_cores': 'numCpuCores',
            'num_vc_instances': 'numVcInstances',
            'virtual_mem_size': 'virtualMemSize'
        }

        self._compute_attributes = compute_attributes
        self._num_cpu_cores = num_cpu_cores
        self._num_vc_instances = num_vc_instances
        self._virtual_mem_size = virtual_mem_size

    @classmethod
    def from_dict(cls, dikt) -> 'CreateComputeResourceReservationRequestComputePoolReservation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateComputeResourceReservationRequest_computePoolReservation of this CreateComputeResourceReservationRequestComputePoolReservation.  # noqa: E501
        :rtype: CreateComputeResourceReservationRequestComputePoolReservation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def compute_attributes(self) -> CreateComputeResourceReservationRequestComputePoolReservationComputeAttributes:
        """Gets the compute_attributes of this CreateComputeResourceReservationRequestComputePoolReservation.


        :return: The compute_attributes of this CreateComputeResourceReservationRequestComputePoolReservation.
        :rtype: CreateComputeResourceReservationRequestComputePoolReservationComputeAttributes
        """
        return self._compute_attributes

    @compute_attributes.setter
    def compute_attributes(self, compute_attributes: CreateComputeResourceReservationRequestComputePoolReservationComputeAttributes):
        """Sets the compute_attributes of this CreateComputeResourceReservationRequestComputePoolReservation.


        :param compute_attributes: The compute_attributes of this CreateComputeResourceReservationRequestComputePoolReservation.
        :type compute_attributes: CreateComputeResourceReservationRequestComputePoolReservationComputeAttributes
        """
        if compute_attributes is None:
            raise ValueError("Invalid value for `compute_attributes`, must not be `None`")  # noqa: E501

        self._compute_attributes = compute_attributes

    @property
    def num_cpu_cores(self) -> int:
        """Gets the num_cpu_cores of this CreateComputeResourceReservationRequestComputePoolReservation.

        Number of CPU cores to be reserved.  # noqa: E501

        :return: The num_cpu_cores of this CreateComputeResourceReservationRequestComputePoolReservation.
        :rtype: int
        """
        return self._num_cpu_cores

    @num_cpu_cores.setter
    def num_cpu_cores(self, num_cpu_cores: int):
        """Sets the num_cpu_cores of this CreateComputeResourceReservationRequestComputePoolReservation.

        Number of CPU cores to be reserved.  # noqa: E501

        :param num_cpu_cores: The num_cpu_cores of this CreateComputeResourceReservationRequestComputePoolReservation.
        :type num_cpu_cores: int
        """
        if num_cpu_cores is None:
            raise ValueError("Invalid value for `num_cpu_cores`, must not be `None`")  # noqa: E501

        self._num_cpu_cores = num_cpu_cores

    @property
    def num_vc_instances(self) -> int:
        """Gets the num_vc_instances of this CreateComputeResourceReservationRequestComputePoolReservation.

        Number of virtualised container instances to be reserved.  # noqa: E501

        :return: The num_vc_instances of this CreateComputeResourceReservationRequestComputePoolReservation.
        :rtype: int
        """
        return self._num_vc_instances

    @num_vc_instances.setter
    def num_vc_instances(self, num_vc_instances: int):
        """Sets the num_vc_instances of this CreateComputeResourceReservationRequestComputePoolReservation.

        Number of virtualised container instances to be reserved.  # noqa: E501

        :param num_vc_instances: The num_vc_instances of this CreateComputeResourceReservationRequestComputePoolReservation.
        :type num_vc_instances: int
        """
        if num_vc_instances is None:
            raise ValueError("Invalid value for `num_vc_instances`, must not be `None`")  # noqa: E501

        self._num_vc_instances = num_vc_instances

    @property
    def virtual_mem_size(self) -> float:
        """Gets the virtual_mem_size of this CreateComputeResourceReservationRequestComputePoolReservation.

        Size of virtual memory to be reserved.  # noqa: E501

        :return: The virtual_mem_size of this CreateComputeResourceReservationRequestComputePoolReservation.
        :rtype: float
        """
        return self._virtual_mem_size

    @virtual_mem_size.setter
    def virtual_mem_size(self, virtual_mem_size: float):
        """Sets the virtual_mem_size of this CreateComputeResourceReservationRequestComputePoolReservation.

        Size of virtual memory to be reserved.  # noqa: E501

        :param virtual_mem_size: The virtual_mem_size of this CreateComputeResourceReservationRequestComputePoolReservation.
        :type virtual_mem_size: float
        """
        if virtual_mem_size is None:
            raise ValueError("Invalid value for `virtual_mem_size`, must not be `None`")  # noqa: E501

        self._virtual_mem_size = virtual_mem_size
