# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from mtp_plugin_kubernetes.models.base_model_ import Model
from mtp_plugin_kubernetes import util


class GatewaysInnerGatewayAttributesNetworkConnectivityEndpoint(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, net_gw_ip_address: str=None, net_gw_interfce_id: float=None):  # noqa: E501
        """GatewaysInnerGatewayAttributesNetworkConnectivityEndpoint - a model defined in Swagger

        :param net_gw_ip_address: The net_gw_ip_address of this GatewaysInnerGatewayAttributesNetworkConnectivityEndpoint.  # noqa: E501
        :type net_gw_ip_address: str
        :param net_gw_interfce_id: The net_gw_interfce_id of this GatewaysInnerGatewayAttributesNetworkConnectivityEndpoint.  # noqa: E501
        :type net_gw_interfce_id: float
        """
        self.swagger_types = {
            'net_gw_ip_address': str,
            'net_gw_interfce_id': float
        }

        self.attribute_map = {
            'net_gw_ip_address': 'netGwIpAddress',
            'net_gw_interfce_id': 'netGwInterfceId'
        }

        self._net_gw_ip_address = net_gw_ip_address
        self._net_gw_interfce_id = net_gw_interfce_id

    @classmethod
    def from_dict(cls, dikt) -> 'GatewaysInnerGatewayAttributesNetworkConnectivityEndpoint':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The gateways_inner_gatewayAttributes_networkConnectivityEndpoint of this GatewaysInnerGatewayAttributesNetworkConnectivityEndpoint.  # noqa: E501
        :rtype: GatewaysInnerGatewayAttributesNetworkConnectivityEndpoint
        """
        return util.deserialize_model(dikt, cls)

    @property
    def net_gw_ip_address(self) -> str:
        """Gets the net_gw_ip_address of this GatewaysInnerGatewayAttributesNetworkConnectivityEndpoint.

        5GT - Reachable Gw IPv4 Address in terms of A.B.C.D (/32).  # noqa: E501

        :return: The net_gw_ip_address of this GatewaysInnerGatewayAttributesNetworkConnectivityEndpoint.
        :rtype: str
        """
        return self._net_gw_ip_address

    @net_gw_ip_address.setter
    def net_gw_ip_address(self, net_gw_ip_address: str):
        """Sets the net_gw_ip_address of this GatewaysInnerGatewayAttributesNetworkConnectivityEndpoint.

        5GT - Reachable Gw IPv4 Address in terms of A.B.C.D (/32).  # noqa: E501

        :param net_gw_ip_address: The net_gw_ip_address of this GatewaysInnerGatewayAttributesNetworkConnectivityEndpoint.
        :type net_gw_ip_address: str
        """
        if net_gw_ip_address is None:
            raise ValueError("Invalid value for `net_gw_ip_address`, must not be `None`")  # noqa: E501

        self._net_gw_ip_address = net_gw_ip_address

    @property
    def net_gw_interfce_id(self) -> float:
        """Gets the net_gw_interfce_id of this GatewaysInnerGatewayAttributesNetworkConnectivityEndpoint.

        5GT - Reachable Gw interface ID.  # noqa: E501

        :return: The net_gw_interfce_id of this GatewaysInnerGatewayAttributesNetworkConnectivityEndpoint.
        :rtype: float
        """
        return self._net_gw_interfce_id

    @net_gw_interfce_id.setter
    def net_gw_interfce_id(self, net_gw_interfce_id: float):
        """Sets the net_gw_interfce_id of this GatewaysInnerGatewayAttributesNetworkConnectivityEndpoint.

        5GT - Reachable Gw interface ID.  # noqa: E501

        :param net_gw_interfce_id: The net_gw_interfce_id of this GatewaysInnerGatewayAttributesNetworkConnectivityEndpoint.
        :type net_gw_interfce_id: float
        """
        if net_gw_interfce_id is None:
            raise ValueError("Invalid value for `net_gw_interfce_id`, must not be `None`")  # noqa: E501

        self._net_gw_interfce_id = net_gw_interfce_id
