# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from mtp_plugin_kubernetes.models.base_model_ import Model
from mtp_plugin_kubernetes import util
from mtp_plugin_kubernetes.models.mec_app_d_info_inner_app_d_attributes import MECAppDInfoInnerAppDAttributes


class MECAppDInfoInner(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, app_d_attributes: MECAppDInfoInnerAppDAttributes=None):  # noqa: E501
        """MECAppDInfoInner - a model defined in Swagger

        :param app_d_attributes: The app_d_attributes of this MECAppDInfoInner.  # noqa: E501
        :type app_d_attributes: MECAppDInfoInnerAppDAttributes
        """
        self.swagger_types = {
            'app_d_attributes': MECAppDInfoInnerAppDAttributes
        }

        self.attribute_map = {
            'app_d_attributes': 'appDAttributes'
        }

        self._app_d_attributes = app_d_attributes

    @classmethod
    def from_dict(cls, dikt) -> 'MECAppDInfoInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MECAppDInfo_inner of this MECAppDInfoInner.  # noqa: E501
        :rtype: MECAppDInfoInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def app_d_attributes(self) -> MECAppDInfoInnerAppDAttributes:
        """Gets the app_d_attributes of this MECAppDInfoInner.


        :return: The app_d_attributes of this MECAppDInfoInner.
        :rtype: MECAppDInfoInnerAppDAttributes
        """
        return self._app_d_attributes

    @app_d_attributes.setter
    def app_d_attributes(self, app_d_attributes: MECAppDInfoInnerAppDAttributes):
        """Sets the app_d_attributes of this MECAppDInfoInner.


        :param app_d_attributes: The app_d_attributes of this MECAppDInfoInner.
        :type app_d_attributes: MECAppDInfoInnerAppDAttributes
        """
        if app_d_attributes is None:
            raise ValueError("Invalid value for `app_d_attributes`, must not be `None`")  # noqa: E501

        self._app_d_attributes = app_d_attributes
