# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from mtp_plugin_kubernetes.models.base_model_ import Model
from mtp_plugin_kubernetes import util


class NetworkIds(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, network_id: str=None):  # noqa: E501
        """NetworkIds - a model defined in Swagger

        :param network_id: The network_id of this NetworkIds.  # noqa: E501
        :type network_id: str
        """
        self.swagger_types = {
            'network_id': str
        }

        self.attribute_map = {
            'network_id': 'networkId'
        }

        self._network_id = network_id

    @classmethod
    def from_dict(cls, dikt) -> 'NetworkIds':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NetworkIds of this NetworkIds.  # noqa: E501
        :rtype: NetworkIds
        """
        return util.deserialize_model(dikt, cls)

    @property
    def network_id(self) -> str:
        """Gets the network_id of this NetworkIds.

        Identifier of the virtualised network resource(s) to be terminated.  # noqa: E501

        :return: The network_id of this NetworkIds.
        :rtype: str
        """
        return self._network_id

    @network_id.setter
    def network_id(self, network_id: str):
        """Sets the network_id of this NetworkIds.

        Identifier of the virtualised network resource(s) to be terminated.  # noqa: E501

        :param network_id: The network_id of this NetworkIds.
        :type network_id: str
        """
        if network_id is None:
            raise ValueError("Invalid value for `network_id`, must not be `None`")  # noqa: E501

        self._network_id = network_id
