# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from mtp_plugin_kubernetes.models.base_model_ import Model
from mtp_plugin_kubernetes import util


class QueryComputeCapacityRequestTimePeriod(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, start_time: datetime=None, stop_time: datetime=None):  # noqa: E501
        """QueryComputeCapacityRequestTimePeriod - a model defined in Swagger

        :param start_time: The start_time of this QueryComputeCapacityRequestTimePeriod.  # noqa: E501
        :type start_time: datetime
        :param stop_time: The stop_time of this QueryComputeCapacityRequestTimePeriod.  # noqa: E501
        :type stop_time: datetime
        """
        self.swagger_types = {
            'start_time': datetime,
            'stop_time': datetime
        }

        self.attribute_map = {
            'start_time': 'startTime',
            'stop_time': 'stopTime'
        }

        self._start_time = start_time
        self._stop_time = stop_time

    @classmethod
    def from_dict(cls, dikt) -> 'QueryComputeCapacityRequestTimePeriod':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The QueryComputeCapacityRequest_timePeriod of this QueryComputeCapacityRequestTimePeriod.  # noqa: E501
        :rtype: QueryComputeCapacityRequestTimePeriod
        """
        return util.deserialize_model(dikt, cls)

    @property
    def start_time(self) -> datetime:
        """Gets the start_time of this QueryComputeCapacityRequestTimePeriod.

        Indication when the capacity query period starts.  # noqa: E501

        :return: The start_time of this QueryComputeCapacityRequestTimePeriod.
        :rtype: datetime
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time: datetime):
        """Sets the start_time of this QueryComputeCapacityRequestTimePeriod.

        Indication when the capacity query period starts.  # noqa: E501

        :param start_time: The start_time of this QueryComputeCapacityRequestTimePeriod.
        :type start_time: datetime
        """
        if start_time is None:
            raise ValueError("Invalid value for `start_time`, must not be `None`")  # noqa: E501

        self._start_time = start_time

    @property
    def stop_time(self) -> datetime:
        """Gets the stop_time of this QueryComputeCapacityRequestTimePeriod.

        Indication when the capacity query period stops.  # noqa: E501

        :return: The stop_time of this QueryComputeCapacityRequestTimePeriod.
        :rtype: datetime
        """
        return self._stop_time

    @stop_time.setter
    def stop_time(self, stop_time: datetime):
        """Sets the stop_time of this QueryComputeCapacityRequestTimePeriod.

        Indication when the capacity query period stops.  # noqa: E501

        :param stop_time: The stop_time of this QueryComputeCapacityRequestTimePeriod.
        :type stop_time: datetime
        """
        if stop_time is None:
            raise ValueError("Invalid value for `stop_time`, must not be `None`")  # noqa: E501

        self._stop_time = stop_time
