# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from mtp_plugin_kubernetes.models.base_model_ import Model
from mtp_plugin_kubernetes.models.meta_data_inner import MetaDataInner  # noqa: F401,E501
from mtp_plugin_kubernetes import util


class ReservedVirtualNetworkNetworkPorts(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, bandwidth: float=None, metadata: List[MetaDataInner]=None, port_id: str=None, port_type: str=None, segment_id: str=None):  # noqa: E501
        """ReservedVirtualNetworkNetworkPorts - a model defined in Swagger

        :param bandwidth: The bandwidth of this ReservedVirtualNetworkNetworkPorts.  # noqa: E501
        :type bandwidth: float
        :param metadata: The metadata of this ReservedVirtualNetworkNetworkPorts.  # noqa: E501
        :type metadata: List[MetaDataInner]
        :param port_id: The port_id of this ReservedVirtualNetworkNetworkPorts.  # noqa: E501
        :type port_id: str
        :param port_type: The port_type of this ReservedVirtualNetworkNetworkPorts.  # noqa: E501
        :type port_type: str
        :param segment_id: The segment_id of this ReservedVirtualNetworkNetworkPorts.  # noqa: E501
        :type segment_id: str
        """
        self.swagger_types = {
            'bandwidth': float,
            'metadata': List[MetaDataInner],
            'port_id': str,
            'port_type': str,
            'segment_id': str
        }

        self.attribute_map = {
            'bandwidth': 'bandwidth',
            'metadata': 'metadata',
            'port_id': 'portId',
            'port_type': 'portType',
            'segment_id': 'segmentId'
        }

        self._bandwidth = bandwidth
        self._metadata = metadata
        self._port_id = port_id
        self._port_type = port_type
        self._segment_id = segment_id

    @classmethod
    def from_dict(cls, dikt) -> 'ReservedVirtualNetworkNetworkPorts':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ReservedVirtualNetwork_networkPorts of this ReservedVirtualNetworkNetworkPorts.  # noqa: E501
        :rtype: ReservedVirtualNetworkNetworkPorts
        """
        return util.deserialize_model(dikt, cls)

    @property
    def bandwidth(self) -> float:
        """Gets the bandwidth of this ReservedVirtualNetworkNetworkPorts.

        The bitrate of the virtual network port (in Mbps)  # noqa: E501

        :return: The bandwidth of this ReservedVirtualNetworkNetworkPorts.
        :rtype: float
        """
        return self._bandwidth

    @bandwidth.setter
    def bandwidth(self, bandwidth: float):
        """Sets the bandwidth of this ReservedVirtualNetworkNetworkPorts.

        The bitrate of the virtual network port (in Mbps)  # noqa: E501

        :param bandwidth: The bandwidth of this ReservedVirtualNetworkNetworkPorts.
        :type bandwidth: float
        """
        if bandwidth is None:
            raise ValueError("Invalid value for `bandwidth`, must not be `None`")  # noqa: E501

        self._bandwidth = bandwidth

    @property
    def metadata(self) -> List[MetaDataInner]:
        """Gets the metadata of this ReservedVirtualNetworkNetworkPorts.

        List of metadata key-value pairs used by the consumer to associate meaningful metadata to the related virtualised resource.  # noqa: E501

        :return: The metadata of this ReservedVirtualNetworkNetworkPorts.
        :rtype: List[MetaDataInner]
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: List[MetaDataInner]):
        """Sets the metadata of this ReservedVirtualNetworkNetworkPorts.

        List of metadata key-value pairs used by the consumer to associate meaningful metadata to the related virtualised resource.  # noqa: E501

        :param metadata: The metadata of this ReservedVirtualNetworkNetworkPorts.
        :type metadata: List[MetaDataInner]
        """

        self._metadata = metadata

    @property
    def port_id(self) -> str:
        """Gets the port_id of this ReservedVirtualNetworkNetworkPorts.

        Identifier of the network port that has been reserved.  # noqa: E501

        :return: The port_id of this ReservedVirtualNetworkNetworkPorts.
        :rtype: str
        """
        return self._port_id

    @port_id.setter
    def port_id(self, port_id: str):
        """Sets the port_id of this ReservedVirtualNetworkNetworkPorts.

        Identifier of the network port that has been reserved.  # noqa: E501

        :param port_id: The port_id of this ReservedVirtualNetworkNetworkPorts.
        :type port_id: str
        """
        if port_id is None:
            raise ValueError("Invalid value for `port_id`, must not be `None`")  # noqa: E501

        self._port_id = port_id

    @property
    def port_type(self) -> str:
        """Gets the port_type of this ReservedVirtualNetworkNetworkPorts.

        Type of network port. Examples of types are access ports, or trunk ports (layer 1) that become transport for multiple layer 2 or layer 3 networks.  # noqa: E501

        :return: The port_type of this ReservedVirtualNetworkNetworkPorts.
        :rtype: str
        """
        return self._port_type

    @port_type.setter
    def port_type(self, port_type: str):
        """Sets the port_type of this ReservedVirtualNetworkNetworkPorts.

        Type of network port. Examples of types are access ports, or trunk ports (layer 1) that become transport for multiple layer 2 or layer 3 networks.  # noqa: E501

        :param port_type: The port_type of this ReservedVirtualNetworkNetworkPorts.
        :type port_type: str
        """
        if port_type is None:
            raise ValueError("Invalid value for `port_type`, must not be `None`")  # noqa: E501

        self._port_type = port_type

    @property
    def segment_id(self) -> str:
        """Gets the segment_id of this ReservedVirtualNetworkNetworkPorts.

        The isolated segment the network port belongs to. For instance, for a \"vlan\", it corresponds to the vlan identifier; and for a \"gre\", this corresponds to a gre key. The cardinality can be 0 to allow for flat networks without any specific segmentation.  # noqa: E501

        :return: The segment_id of this ReservedVirtualNetworkNetworkPorts.
        :rtype: str
        """
        return self._segment_id

    @segment_id.setter
    def segment_id(self, segment_id: str):
        """Sets the segment_id of this ReservedVirtualNetworkNetworkPorts.

        The isolated segment the network port belongs to. For instance, for a \"vlan\", it corresponds to the vlan identifier; and for a \"gre\", this corresponds to a gre key. The cardinality can be 0 to allow for flat networks without any specific segmentation.  # noqa: E501

        :param segment_id: The segment_id of this ReservedVirtualNetworkNetworkPorts.
        :type segment_id: str
        """
        if segment_id is None:
            raise ValueError("Invalid value for `segment_id`, must not be `None`")  # noqa: E501

        self._segment_id = segment_id
