SET FOREIGN_KEY_CHECKS=0; 
DROP database mtpabstrdb;
SET FOREIGN_KEY_CHECKS=0; 
DROP database mtpdomdb;
SET FOREIGN_KEY_CHECKS=0; 
DROP database mtpservdb;
SET FOREIGN_KEY_CHECKS=0; 
DROP database mtpappddb;
SET FOREIGN_KEY_CHECKS=0; 
DROP database mtpfeddb;
