FROM ubuntu:16.04

RUN apt-get update 
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install openjdk-8-jdk

RUN mkdir -p /usr/src/app
COPY . /usr/src/app
WORKDIR /usr/src/app/xml_domain

# JAVA env vars
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64
ENV PATH $JAVA_HOME/bin:$PATH

EXPOSE 53000

ENTRYPOINT ["java"]

CMD ["-jar", "../target/DummyWIMPlugin-1.0.jar", "domaininfo.xml", "wimplugin", "53000"]
