/*
 * 5GT-MTP PA API
 * REST-API for the MTP PA. Find more at http://5g-transformer.eu
 *
 * OpenAPI spec version: 0.0.0
 * Contact: cnd@lists.cttc.es
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.mtp.extinterface.pa.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.mtp.extinterface.pa.swagger.client.model.CompRouteOutputZoneAtts;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * CompRouteOutputNfviPopResp
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-05-02T08:45:54.546Z")
public class CompRouteOutputNfviPopResp {
  @SerializedName("vimId")
  private String vimId = null;

  @SerializedName("nfviPopId")
  private String nfviPopId = null;

  @SerializedName("zoneAtts")
  private List<CompRouteOutputZoneAtts> zoneAtts = new ArrayList<CompRouteOutputZoneAtts>();

  public CompRouteOutputNfviPopResp vimId(String vimId) {
    this.vimId = vimId;
    return this;
  }

   /**
   * Identifier of the VIM
   * @return vimId
  **/
  @ApiModelProperty(required = true, value = "Identifier of the VIM")
  public String getVimId() {
    return vimId;
  }

  public void setVimId(String vimId) {
    this.vimId = vimId;
  }

  public CompRouteOutputNfviPopResp nfviPopId(String nfviPopId) {
    this.nfviPopId = nfviPopId;
    return this;
  }

   /**
   * Identifier of the NFVI-PoP
   * @return nfviPopId
  **/
  @ApiModelProperty(required = true, value = "Identifier of the NFVI-PoP")
  public String getNfviPopId() {
    return nfviPopId;
  }

  public void setNfviPopId(String nfviPopId) {
    this.nfviPopId = nfviPopId;
  }

  public CompRouteOutputNfviPopResp zoneAtts(List<CompRouteOutputZoneAtts> zoneAtts) {
    this.zoneAtts = zoneAtts;
    return this;
  }

  public CompRouteOutputNfviPopResp addZoneAttsItem(CompRouteOutputZoneAtts zoneAttsItem) {
    this.zoneAtts.add(zoneAttsItem);
    return this;
  }

   /**
   * Get zoneAtts
   * @return zoneAtts
  **/
  @ApiModelProperty(required = true, value = "")
  public List<CompRouteOutputZoneAtts> getZoneAtts() {
    return zoneAtts;
  }

  public void setZoneAtts(List<CompRouteOutputZoneAtts> zoneAtts) {
    this.zoneAtts = zoneAtts;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CompRouteOutputNfviPopResp compRouteOutputNfviPopResp = (CompRouteOutputNfviPopResp) o;
    return Objects.equals(this.vimId, compRouteOutputNfviPopResp.vimId) &&
        Objects.equals(this.nfviPopId, compRouteOutputNfviPopResp.nfviPopId) &&
        Objects.equals(this.zoneAtts, compRouteOutputNfviPopResp.zoneAtts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(vimId, nfviPopId, zoneAtts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CompRouteOutputNfviPopResp {\n");
    
    sb.append("    vimId: ").append(toIndentedString(vimId)).append("\n");
    sb.append("    nfviPopId: ").append(toIndentedString(nfviPopId)).append("\n");
    sb.append("    zoneAtts: ").append(toIndentedString(zoneAtts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

