/*
 * MTP Manager API
 * MTP Manager API
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import com.rl.extinterface.nbi.swagger.model.InlineResponse200;
import com.rl.extinterface.nbi.swagger.model.MECTrafficServiceCreationRequest;
import com.rl.extinterface.nbi.swagger.model.MECTrafficServiceCreationResponse;
import io.swagger.client.ApiException;

import org.junit.Test;
import org.junit.Ignore;

import java.util.List;

/**
 * API tests for MecResourcesApi
 */
@Ignore
public class MecResourcesApiTest {

    private final MecResourcesApi api = new MecResourcesApi();

    
    /**
     * Retrieve a list of all covered regions.
     *
     * Retrieve a list of MEC regions, reporting their identifiers and location information.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void serviceRegionsGetTest() throws ApiException {
        InlineResponse200 response = api.serviceRegionsGet();

        // TODO: test validations
    }
    
    /**
     * Retrieve a list of MEC service requests for the given region.
     *
     * Retrieve a list of MEC service requests for the given region.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void serviceRegionsRegionIdGetTest() throws ApiException {
        String regionId = null;
        List<MECTrafficServiceCreationRequest> response = api.serviceRegionsRegionIdGet(regionId);

        // TODO: test validations
    }
    
    /**
     * Retrieve a list of MEC service requests.
     *
     * Retrieve a list of MEC service requests.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void serviceRequestsGetTest() throws ApiException {
        List<MECTrafficServiceCreationRequest> response = api.serviceRequestsGet();

        // TODO: test validations
    }
    
    /**
     * Create MEC service rules.
     *
     * Create MEC service rules.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void serviceRequestsPostTest() throws ApiException {
        MECTrafficServiceCreationRequest mecTrafficServiceCreationRequest = null;
        MECTrafficServiceCreationResponse response = api.serviceRequestsPost(mecTrafficServiceCreationRequest);

        // TODO: test validations
    }
    
    /**
     * Delete service.
     *
     * Delete service identified by the given request ID.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void serviceRequestsRequestIdDeleteTest() throws ApiException {
        String requestId = null;
        api.serviceRequestsRequestIdDelete(requestId);

        // TODO: test validations
    }
    
    /**
     * Retrieve information about a MEC service request.
     *
     * Retrieve information about a MEC service request.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void serviceRequestsRequestIdGetTest() throws ApiException {
        String requestId = null;
        MECTrafficServiceCreationRequest response = api.serviceRequestsRequestIdGet(requestId);

        // TODO: test validations
    }
    
}
