/*
 * MTP Manager API
 * MTP Manager API
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.rl.extinterface.nbi.swagger.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.rl.extinterface.nbi.swagger.model.MetaData;
import com.rl.extinterface.nbi.swagger.model.SubnetData;
import java.io.IOException;

/**
 * AllocateNetworkRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-11-12T12:38:09.537Z")



public class AllocateNetworkRequest {
  @SerializedName("affinityOrAntiAffinityConstraints")
  private String affinityOrAntiAffinityConstraints = null;

  @SerializedName("locationConstraints")
  private String locationConstraints = null;

  @SerializedName("metadata")
  private MetaData metadata = null;

  @SerializedName("networkResourceName")
  private String networkResourceName = null;

  @SerializedName("networkResourceType")
  private String networkResourceType = null;

  @SerializedName("reservationId")
  private String reservationId = null;

  @SerializedName("resourceGroupId")
  private String resourceGroupId = null;

  @SerializedName("typeNetworkData")
  private String typeNetworkData = null;

  @SerializedName("typeNetworkPortData")
  private String typeNetworkPortData = null;

  @SerializedName("typeSubnetData")
  private SubnetData typeSubnetData = null;

  public AllocateNetworkRequest affinityOrAntiAffinityConstraints(String affinityOrAntiAffinityConstraints) {
    this.affinityOrAntiAffinityConstraints = affinityOrAntiAffinityConstraints;
    return this;
  }

   /**
   * The binary software image file.
   * @return affinityOrAntiAffinityConstraints
  **/
  @ApiModelProperty(required = true, value = "The binary software image file.")
  public String getAffinityOrAntiAffinityConstraints() {
    return affinityOrAntiAffinityConstraints;
  }

  public void setAffinityOrAntiAffinityConstraints(String affinityOrAntiAffinityConstraints) {
    this.affinityOrAntiAffinityConstraints = affinityOrAntiAffinityConstraints;
  }

  public AllocateNetworkRequest locationConstraints(String locationConstraints) {
    this.locationConstraints = locationConstraints;
    return this;
  }

   /**
   * Controls the visibility of the image. In case of \&quot;private\&quot; value the image is available only for the tenant assigned to the provided resourceGroupId and the administrator tenants of the VIM while in case of \&quot;public\&quot; value, all tenants of the VIM can use the image.
   * @return locationConstraints
  **/
  @ApiModelProperty(required = true, value = "Controls the visibility of the image. In case of \"private\" value the image is available only for the tenant assigned to the provided resourceGroupId and the administrator tenants of the VIM while in case of \"public\" value, all tenants of the VIM can use the image.")
  public String getLocationConstraints() {
    return locationConstraints;
  }

  public void setLocationConstraints(String locationConstraints) {
    this.locationConstraints = locationConstraints;
  }

  public AllocateNetworkRequest metadata(MetaData metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @ApiModelProperty(required = true, value = "")
  public MetaData getMetadata() {
    return metadata;
  }

  public void setMetadata(MetaData metadata) {
    this.metadata = metadata;
  }

  public AllocateNetworkRequest networkResourceName(String networkResourceName) {
    this.networkResourceName = networkResourceName;
    return this;
  }

   /**
   * Name provided by the consumer for the virtualised network resource to allocate. It can be used for identifying resources from consumer side.
   * @return networkResourceName
  **/
  @ApiModelProperty(required = true, value = "Name provided by the consumer for the virtualised network resource to allocate. It can be used for identifying resources from consumer side.")
  public String getNetworkResourceName() {
    return networkResourceName;
  }

  public void setNetworkResourceName(String networkResourceName) {
    this.networkResourceName = networkResourceName;
  }

  public AllocateNetworkRequest networkResourceType(String networkResourceType) {
    this.networkResourceType = networkResourceType;
    return this;
  }

   /**
   * Type of virtualised network resource. Possible values are: \&quot;network\&quot;, \&quot;subnet\&quot; or network-port.
   * @return networkResourceType
  **/
  @ApiModelProperty(required = true, value = "Type of virtualised network resource. Possible values are: \"network\", \"subnet\" or network-port.")
  public String getNetworkResourceType() {
    return networkResourceType;
  }

  public void setNetworkResourceType(String networkResourceType) {
    this.networkResourceType = networkResourceType;
  }

  public AllocateNetworkRequest reservationId(String reservationId) {
    this.reservationId = reservationId;
    return this;
  }

   /**
   * Identifier of the resource reservation applicable to this virtualised resource management operation.
   * @return reservationId
  **/
  @ApiModelProperty(required = true, value = "Identifier of the resource reservation applicable to this virtualised resource management operation.")
  public String getReservationId() {
    return reservationId;
  }

  public void setReservationId(String reservationId) {
    this.reservationId = reservationId;
  }

  public AllocateNetworkRequest resourceGroupId(String resourceGroupId) {
    this.resourceGroupId = resourceGroupId;
    return this;
  }

   /**
   * Unique identifier of the \&quot;infrastructure resource group\&quot;, logical grouping of virtual resources assigned to a tenant within an Infrastructure Domain.
   * @return resourceGroupId
  **/
  @ApiModelProperty(required = true, value = "Unique identifier of the \"infrastructure resource group\", logical grouping of virtual resources assigned to a tenant within an Infrastructure Domain.")
  public String getResourceGroupId() {
    return resourceGroupId;
  }

  public void setResourceGroupId(String resourceGroupId) {
    this.resourceGroupId = resourceGroupId;
  }

  public AllocateNetworkRequest typeNetworkData(String typeNetworkData) {
    this.typeNetworkData = typeNetworkData;
    return this;
  }

   /**
   * The network data provides information about the particular virtual network resource to create. Cardinality can be \&quot;0\&quot; depending on the value of networkResourceType.
   * @return typeNetworkData
  **/
  @ApiModelProperty(required = true, value = "The network data provides information about the particular virtual network resource to create. Cardinality can be \"0\" depending on the value of networkResourceType.")
  public String getTypeNetworkData() {
    return typeNetworkData;
  }

  public void setTypeNetworkData(String typeNetworkData) {
    this.typeNetworkData = typeNetworkData;
  }

  public AllocateNetworkRequest typeNetworkPortData(String typeNetworkPortData) {
    this.typeNetworkPortData = typeNetworkPortData;
    return this;
  }

   /**
   * The binary software image file.
   * @return typeNetworkPortData
  **/
  @ApiModelProperty(required = true, value = "The binary software image file.")
  public String getTypeNetworkPortData() {
    return typeNetworkPortData;
  }

  public void setTypeNetworkPortData(String typeNetworkPortData) {
    this.typeNetworkPortData = typeNetworkPortData;
  }

  public AllocateNetworkRequest typeSubnetData(SubnetData typeSubnetData) {
    this.typeSubnetData = typeSubnetData;
    return this;
  }

   /**
   * The binary software image file.
   * @return typeSubnetData
  **/
  @ApiModelProperty(required = true, value = "The binary software image file.")
  public SubnetData getTypeSubnetData() {
    return typeSubnetData;
  }

  public void setTypeSubnetData(SubnetData typeSubnetData) {
    this.typeSubnetData = typeSubnetData;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AllocateNetworkRequest allocateNetworkRequest = (AllocateNetworkRequest) o;
    return Objects.equals(this.affinityOrAntiAffinityConstraints, allocateNetworkRequest.affinityOrAntiAffinityConstraints) &&
        Objects.equals(this.locationConstraints, allocateNetworkRequest.locationConstraints) &&
        Objects.equals(this.metadata, allocateNetworkRequest.metadata) &&
        Objects.equals(this.networkResourceName, allocateNetworkRequest.networkResourceName) &&
        Objects.equals(this.networkResourceType, allocateNetworkRequest.networkResourceType) &&
        Objects.equals(this.reservationId, allocateNetworkRequest.reservationId) &&
        Objects.equals(this.resourceGroupId, allocateNetworkRequest.resourceGroupId) &&
        Objects.equals(this.typeNetworkData, allocateNetworkRequest.typeNetworkData) &&
        Objects.equals(this.typeNetworkPortData, allocateNetworkRequest.typeNetworkPortData) &&
        Objects.equals(this.typeSubnetData, allocateNetworkRequest.typeSubnetData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(affinityOrAntiAffinityConstraints, locationConstraints, metadata, networkResourceName, networkResourceType, reservationId, resourceGroupId, typeNetworkData, typeNetworkPortData, typeSubnetData);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AllocateNetworkRequest {\n");
    
    sb.append("    affinityOrAntiAffinityConstraints: ").append(toIndentedString(affinityOrAntiAffinityConstraints)).append("\n");
    sb.append("    locationConstraints: ").append(toIndentedString(locationConstraints)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    networkResourceName: ").append(toIndentedString(networkResourceName)).append("\n");
    sb.append("    networkResourceType: ").append(toIndentedString(networkResourceType)).append("\n");
    sb.append("    reservationId: ").append(toIndentedString(reservationId)).append("\n");
    sb.append("    resourceGroupId: ").append(toIndentedString(resourceGroupId)).append("\n");
    sb.append("    typeNetworkData: ").append(toIndentedString(typeNetworkData)).append("\n");
    sb.append("    typeNetworkPortData: ").append(toIndentedString(typeNetworkPortData)).append("\n");
    sb.append("    typeSubnetData: ").append(toIndentedString(typeSubnetData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

