/*
 * MTP Manager API
 * MTP Manager API
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.rl.extinterface.nbi.swagger.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Element containing user data to customize the virtualised compute resource at boot-time.
 */
@ApiModel(description = "Element containing user data to customize the virtualised compute resource at boot-time.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-08T16:03:30.222Z")
public class AllocateComputeRequestUserData {
  @SerializedName("content")
  private String content = null;

  @SerializedName("method")
  private String method = null;

  public AllocateComputeRequestUserData content(String content) {
    this.content = content;
    return this;
  }

   /**
   * String containing the user data to customize a virtualised compute resource at boot-time.
   * @return content
  **/
  @ApiModelProperty(required = true, value = "String containing the user data to customize a virtualised compute resource at boot-time.")
  public String getContent() {
    return content;
  }

  public void setContent(String content) {
    this.content = content;
  }

  public AllocateComputeRequestUserData method(String method) {
    this.method = method;
    return this;
  }

   /**
   * Method used as transportation media to convey the content of the UserData to the virtualised compute resource. Possible values: CONFIG-DRIVE.
   * @return method
  **/
  @ApiModelProperty(required = true, value = "Method used as transportation media to convey the content of the UserData to the virtualised compute resource. Possible values: CONFIG-DRIVE.")
  public String getMethod() {
    return method;
  }

  public void setMethod(String method) {
    this.method = method;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AllocateComputeRequestUserData allocateComputeRequestUserData = (AllocateComputeRequestUserData) o;
    return Objects.equals(this.content, allocateComputeRequestUserData.content) &&
        Objects.equals(this.method, allocateComputeRequestUserData.method);
  }

  @Override
  public int hashCode() {
    return Objects.hash(content, method);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AllocateComputeRequestUserData {\n");
    
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    method: ").append(toIndentedString(method)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

