/*
 * MTP Manager API
 * MTP Manager API
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.rl.extinterface.nbi.swagger.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * AllocateNetworkResultNetworkDataNetworkQoS
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-08T16:03:30.222Z")
public class AllocateNetworkResultNetworkDataNetworkQoS {
  @SerializedName("qosName")
  private String qosName = null;

  @SerializedName("qosValue")
  private String qosValue = null;

  public AllocateNetworkResultNetworkDataNetworkQoS qosName(String qosName) {
    this.qosName = qosName;
    return this;
  }

   /**
   * Name given to the QoS parameter.
   * @return qosName
  **/
  @ApiModelProperty(required = true, value = "Name given to the QoS parameter.")
  public String getQosName() {
    return qosName;
  }

  public void setQosName(String qosName) {
    this.qosName = qosName;
  }

  public AllocateNetworkResultNetworkDataNetworkQoS qosValue(String qosValue) {
    this.qosValue = qosValue;
    return this;
  }

   /**
   * Value of the QoS parameter.
   * @return qosValue
  **/
  @ApiModelProperty(required = true, value = "Value of the QoS parameter.")
  public String getQosValue() {
    return qosValue;
  }

  public void setQosValue(String qosValue) {
    this.qosValue = qosValue;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AllocateNetworkResultNetworkDataNetworkQoS allocateNetworkResultNetworkDataNetworkQoS = (AllocateNetworkResultNetworkDataNetworkQoS) o;
    return Objects.equals(this.qosName, allocateNetworkResultNetworkDataNetworkQoS.qosName) &&
        Objects.equals(this.qosValue, allocateNetworkResultNetworkDataNetworkQoS.qosValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(qosName, qosValue);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AllocateNetworkResultNetworkDataNetworkQoS {\n");
    
    sb.append("    qosName: ").append(toIndentedString(qosName)).append("\n");
    sb.append("    qosValue: ").append(toIndentedString(qosValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

