/*
 * MTP Manager API
 * MTP Manager API
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.rl.extinterface.nbi.swagger.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;

/**
 * This is used to describe the maximum latency tolerated by the mobile edge application.
 */
@ApiModel(description = "This is used to describe the maximum latency tolerated by the mobile edge application.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-08T16:03:30.222Z")
public class LatencyDescriptor {
  @SerializedName("timeUnit")
  private String timeUnit = null;

  @SerializedName("latency")
  private BigDecimal latency = null;

  public LatencyDescriptor timeUnit(String timeUnit) {
    this.timeUnit = timeUnit;
    return this;
  }

   /**
   * Time unit, e.g., ms
   * @return timeUnit
  **/
  @ApiModelProperty(required = true, value = "Time unit, e.g., ms")
  public String getTimeUnit() {
    return timeUnit;
  }

  public void setTimeUnit(String timeUnit) {
    this.timeUnit = timeUnit;
  }

  public LatencyDescriptor latency(BigDecimal latency) {
    this.latency = latency;
    return this;
  }

   /**
   * The value of the latency
   * @return latency
  **/
  @ApiModelProperty(required = true, value = "The value of the latency")
  public BigDecimal getLatency() {
    return latency;
  }

  public void setLatency(BigDecimal latency) {
    this.latency = latency;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LatencyDescriptor latencyDescriptor = (LatencyDescriptor) o;
    return Objects.equals(this.timeUnit, latencyDescriptor.timeUnit) &&
        Objects.equals(this.latency, latencyDescriptor.latency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timeUnit, latency);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LatencyDescriptor {\n");
    
    sb.append("    timeUnit: ").append(toIndentedString(timeUnit)).append("\n");
    sb.append("    latency: ").append(toIndentedString(latency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

