/*
 * MTP Manager API
 * MTP Manager API
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.rl.extinterface.nbi.swagger.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * 5GT - Element providing information about Quality of Service attributes (cost and delay) that the network shall support.
 */
@ApiModel(description = "5GT - Element providing information about Quality of Service attributes (cost and delay) that the network shall support.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-11-12T12:38:09.537Z")



public class LogicalLinkInterNfviPopsInnerLogicalLinksNetworkQoS {
  @SerializedName("linkCostValue")
  private BigDecimal linkCostValue = null;

  @SerializedName("linkCost")
  private String linkCost = null;

  @SerializedName("linkDelayValue")
  private BigDecimal linkDelayValue = null;

  @SerializedName("linkDelay")
  private String linkDelay = null;

  public LogicalLinkInterNfviPopsInnerLogicalLinksNetworkQoS linkCostValue(BigDecimal linkCostValue) {
    this.linkCostValue = linkCostValue;
    return this;
  }

   /**
   * 5GT - Value of Link Cost
   * @return linkCostValue
  **/
  @ApiModelProperty(required = true, value = "5GT - Value of Link Cost")
  public BigDecimal getLinkCostValue() {
    return linkCostValue;
  }

  public void setLinkCostValue(BigDecimal linkCostValue) {
    this.linkCostValue = linkCostValue;
  }

  public LogicalLinkInterNfviPopsInnerLogicalLinksNetworkQoS linkCost(String linkCost) {
    this.linkCost = linkCost;
    return this;
  }

   /**
   * 5GT - Link cost name .
   * @return linkCost
  **/
  @ApiModelProperty(required = true, value = "5GT - Link cost name .")
  public String getLinkCost() {
    return linkCost;
  }

  public void setLinkCost(String linkCost) {
    this.linkCost = linkCost;
  }

  public LogicalLinkInterNfviPopsInnerLogicalLinksNetworkQoS linkDelayValue(BigDecimal linkDelayValue) {
    this.linkDelayValue = linkDelayValue;
    return this;
  }

   /**
   * 5GT - Value of Link Delay (expressed in ms)
   * @return linkDelayValue
  **/
  @ApiModelProperty(required = true, value = "5GT - Value of Link Delay (expressed in ms)")
  public BigDecimal getLinkDelayValue() {
    return linkDelayValue;
  }

  public void setLinkDelayValue(BigDecimal linkDelayValue) {
    this.linkDelayValue = linkDelayValue;
  }

  public LogicalLinkInterNfviPopsInnerLogicalLinksNetworkQoS linkDelay(String linkDelay) {
    this.linkDelay = linkDelay;
    return this;
  }

   /**
   * 5GT - Link delay name.
   * @return linkDelay
  **/
  @ApiModelProperty(required = true, value = "5GT - Link delay name.")
  public String getLinkDelay() {
    return linkDelay;
  }

  public void setLinkDelay(String linkDelay) {
    this.linkDelay = linkDelay;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LogicalLinkInterNfviPopsInnerLogicalLinksNetworkQoS logicalLinkInterNfviPopsInnerLogicalLinksNetworkQoS = (LogicalLinkInterNfviPopsInnerLogicalLinksNetworkQoS) o;
    return Objects.equals(this.linkCostValue, logicalLinkInterNfviPopsInnerLogicalLinksNetworkQoS.linkCostValue) &&
        Objects.equals(this.linkCost, logicalLinkInterNfviPopsInnerLogicalLinksNetworkQoS.linkCost) &&
        Objects.equals(this.linkDelayValue, logicalLinkInterNfviPopsInnerLogicalLinksNetworkQoS.linkDelayValue) &&
        Objects.equals(this.linkDelay, logicalLinkInterNfviPopsInnerLogicalLinksNetworkQoS.linkDelay);
  }

  @Override
  public int hashCode() {
    return Objects.hash(linkCostValue, linkCost, linkDelayValue, linkDelay);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LogicalLinkInterNfviPopsInnerLogicalLinksNetworkQoS {\n");
    
    sb.append("    linkCostValue: ").append(toIndentedString(linkCostValue)).append("\n");
    sb.append("    linkCost: ").append(toIndentedString(linkCost)).append("\n");
    sb.append("    linkDelayValue: ").append(toIndentedString(linkDelayValue)).append("\n");
    sb.append("    linkDelay: ").append(toIndentedString(linkDelay)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

