/*
 * MTP Manager API
 * MTP Manager API
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.rl.extinterface.nbi.swagger.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;

/**
 * 5GT - Element providing information the attributes related to particular logical links between pair of NFVI-PoPs.
 */
@ApiModel(description = "5GT - Element providing information the attributes related to particular logical links between pair of NFVI-PoPs.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-08T16:03:30.222Z")
public class LogicalLinkInterNfviPopsInnerLogicalLinks {
  @SerializedName("logicalLinkId")
  private String logicalLinkId = null;

  @SerializedName("totalBandwidth")
  private BigDecimal totalBandwidth = null;

  @SerializedName("availableBandwidth")
  private BigDecimal availableBandwidth = null;

  @SerializedName("networkQoS")
  private LogicalLinkInterNfviPopsInnerLogicalLinksNetworkQoS networkQoS = null;

  @SerializedName("srcGwIpAddress")
  private String srcGwIpAddress = null;

  @SerializedName("localLinkId")
  private Integer localLinkId = null;

  @SerializedName("dstGwIpAddress")
  private String dstGwIpAddress = null;

  @SerializedName("remoteLinkId")
  private Integer remoteLinkId = null;

  @SerializedName("networkLayer")
  private String networkLayer = null;

  @SerializedName("interNfviPopNetworkType")
  private String interNfviPopNetworkType = null;

  @SerializedName("interNfviPopNetworkTopology")
  private String interNfviPopNetworkTopology = null;

  public LogicalLinkInterNfviPopsInnerLogicalLinks logicalLinkId(String logicalLinkId) {
    this.logicalLinkId = logicalLinkId;
    return this;
  }

   /**
   * (numbered) Identifier of the logical link
   * @return logicalLinkId
  **/
  @ApiModelProperty(required = true, value = "(numbered) Identifier of the logical link")
  public String getLogicalLinkId() {
    return logicalLinkId;
  }

  public void setLogicalLinkId(String logicalLinkId) {
    this.logicalLinkId = logicalLinkId;
  }

  public LogicalLinkInterNfviPopsInnerLogicalLinks totalBandwidth(BigDecimal totalBandwidth) {
    this.totalBandwidth = totalBandwidth;
    return this;
  }

   /**
   * Total bandwidth capacity supported by the logical link (in Mbps).
   * @return totalBandwidth
  **/
  @ApiModelProperty(required = true, value = "Total bandwidth capacity supported by the logical link (in Mbps).")
  public BigDecimal getTotalBandwidth() {
    return totalBandwidth;
  }

  public void setTotalBandwidth(BigDecimal totalBandwidth) {
    this.totalBandwidth = totalBandwidth;
  }

  public LogicalLinkInterNfviPopsInnerLogicalLinks availableBandwidth(BigDecimal availableBandwidth) {
    this.availableBandwidth = availableBandwidth;
    return this;
  }

   /**
   * Available bandwidth capacity supported by the logical link (in Mbps).
   * @return availableBandwidth
  **/
  @ApiModelProperty(required = true, value = "Available bandwidth capacity supported by the logical link (in Mbps).")
  public BigDecimal getAvailableBandwidth() {
    return availableBandwidth;
  }

  public void setAvailableBandwidth(BigDecimal availableBandwidth) {
    this.availableBandwidth = availableBandwidth;
  }

  public LogicalLinkInterNfviPopsInnerLogicalLinks networkQoS(LogicalLinkInterNfviPopsInnerLogicalLinksNetworkQoS networkQoS) {
    this.networkQoS = networkQoS;
    return this;
  }

   /**
   * Get networkQoS
   * @return networkQoS
  **/
  @ApiModelProperty(required = true, value = "")
  public LogicalLinkInterNfviPopsInnerLogicalLinksNetworkQoS getNetworkQoS() {
    return networkQoS;
  }

  public void setNetworkQoS(LogicalLinkInterNfviPopsInnerLogicalLinksNetworkQoS networkQoS) {
    this.networkQoS = networkQoS;
  }

  public LogicalLinkInterNfviPopsInnerLogicalLinks srcGwIpAddress(String srcGwIpAddress) {
    this.srcGwIpAddress = srcGwIpAddress;
    return this;
  }

   /**
   * 5GT - Source NFVI-PoP Gw IPv4 Address in terms of A.B.C.D (/32).
   * @return srcGwIpAddress
  **/
  @ApiModelProperty(required = true, value = "5GT - Source NFVI-PoP Gw IPv4 Address in terms of A.B.C.D (/32).")
  public String getSrcGwIpAddress() {
    return srcGwIpAddress;
  }

  public void setSrcGwIpAddress(String srcGwIpAddress) {
    this.srcGwIpAddress = srcGwIpAddress;
  }

  public LogicalLinkInterNfviPopsInnerLogicalLinks localLinkId(Integer localLinkId) {
    this.localLinkId = localLinkId;
    return this;
  }

   /**
   * Local Logical Link Id.
   * @return localLinkId
  **/
  @ApiModelProperty(required = true, value = "Local Logical Link Id.")
  public Integer getLocalLinkId() {
    return localLinkId;
  }

  public void setLocalLinkId(Integer localLinkId) {
    this.localLinkId = localLinkId;
  }

  public LogicalLinkInterNfviPopsInnerLogicalLinks dstGwIpAddress(String dstGwIpAddress) {
    this.dstGwIpAddress = dstGwIpAddress;
    return this;
  }

   /**
   * 5GT - Destination NFVI-PoP Gw IPv4 Address in terms of A.B.C.D (/32).
   * @return dstGwIpAddress
  **/
  @ApiModelProperty(required = true, value = "5GT - Destination NFVI-PoP Gw IPv4 Address in terms of A.B.C.D (/32).")
  public String getDstGwIpAddress() {
    return dstGwIpAddress;
  }

  public void setDstGwIpAddress(String dstGwIpAddress) {
    this.dstGwIpAddress = dstGwIpAddress;
  }

  public LogicalLinkInterNfviPopsInnerLogicalLinks remoteLinkId(Integer remoteLinkId) {
    this.remoteLinkId = remoteLinkId;
    return this;
  }

   /**
   * Remote Logical Link Id.
   * @return remoteLinkId
  **/
  @ApiModelProperty(required = true, value = "Remote Logical Link Id.")
  public Integer getRemoteLinkId() {
    return remoteLinkId;
  }

  public void setRemoteLinkId(Integer remoteLinkId) {
    this.remoteLinkId = remoteLinkId;
  }

  public LogicalLinkInterNfviPopsInnerLogicalLinks networkLayer(String networkLayer) {
    this.networkLayer = networkLayer;
    return this;
  }

   /**
   * Get networkLayer
   * @return networkLayer
  **/
  @ApiModelProperty(required = true, value = "")
  public String getNetworkLayer() {
    return networkLayer;
  }

  public void setNetworkLayer(String networkLayer) {
    this.networkLayer = networkLayer;
  }

  public LogicalLinkInterNfviPopsInnerLogicalLinks interNfviPopNetworkType(String interNfviPopNetworkType) {
    this.interNfviPopNetworkType = interNfviPopNetworkType;
    return this;
  }

   /**
   * Get interNfviPopNetworkType
   * @return interNfviPopNetworkType
  **/
  @ApiModelProperty(required = true, value = "")
  public String getInterNfviPopNetworkType() {
    return interNfviPopNetworkType;
  }

  public void setInterNfviPopNetworkType(String interNfviPopNetworkType) {
    this.interNfviPopNetworkType = interNfviPopNetworkType;
  }

  public LogicalLinkInterNfviPopsInnerLogicalLinks interNfviPopNetworkTopology(String interNfviPopNetworkTopology) {
    this.interNfviPopNetworkTopology = interNfviPopNetworkTopology;
    return this;
  }

   /**
   * Get interNfviPopNetworkTopology
   * @return interNfviPopNetworkTopology
  **/
  @ApiModelProperty(required = true, value = "")
  public String getInterNfviPopNetworkTopology() {
    return interNfviPopNetworkTopology;
  }

  public void setInterNfviPopNetworkTopology(String interNfviPopNetworkTopology) {
    this.interNfviPopNetworkTopology = interNfviPopNetworkTopology;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LogicalLinkInterNfviPopsInnerLogicalLinks logicalLinkInterNfviPopsInnerLogicalLinks = (LogicalLinkInterNfviPopsInnerLogicalLinks) o;
    return Objects.equals(this.logicalLinkId, logicalLinkInterNfviPopsInnerLogicalLinks.logicalLinkId) &&
        Objects.equals(this.totalBandwidth, logicalLinkInterNfviPopsInnerLogicalLinks.totalBandwidth) &&
        Objects.equals(this.availableBandwidth, logicalLinkInterNfviPopsInnerLogicalLinks.availableBandwidth) &&
        Objects.equals(this.networkQoS, logicalLinkInterNfviPopsInnerLogicalLinks.networkQoS) &&
        Objects.equals(this.srcGwIpAddress, logicalLinkInterNfviPopsInnerLogicalLinks.srcGwIpAddress) &&
        Objects.equals(this.localLinkId, logicalLinkInterNfviPopsInnerLogicalLinks.localLinkId) &&
        Objects.equals(this.dstGwIpAddress, logicalLinkInterNfviPopsInnerLogicalLinks.dstGwIpAddress) &&
        Objects.equals(this.remoteLinkId, logicalLinkInterNfviPopsInnerLogicalLinks.remoteLinkId) &&
        Objects.equals(this.networkLayer, logicalLinkInterNfviPopsInnerLogicalLinks.networkLayer) &&
        Objects.equals(this.interNfviPopNetworkType, logicalLinkInterNfviPopsInnerLogicalLinks.interNfviPopNetworkType) &&
        Objects.equals(this.interNfviPopNetworkTopology, logicalLinkInterNfviPopsInnerLogicalLinks.interNfviPopNetworkTopology);
  }

  @Override
  public int hashCode() {
    return Objects.hash(logicalLinkId, totalBandwidth, availableBandwidth, networkQoS, srcGwIpAddress, localLinkId, dstGwIpAddress, remoteLinkId, networkLayer, interNfviPopNetworkType, interNfviPopNetworkTopology);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LogicalLinkInterNfviPopsInnerLogicalLinks {\n");
    
    sb.append("    logicalLinkId: ").append(toIndentedString(logicalLinkId)).append("\n");
    sb.append("    totalBandwidth: ").append(toIndentedString(totalBandwidth)).append("\n");
    sb.append("    availableBandwidth: ").append(toIndentedString(availableBandwidth)).append("\n");
    sb.append("    networkQoS: ").append(toIndentedString(networkQoS)).append("\n");
    sb.append("    srcGwIpAddress: ").append(toIndentedString(srcGwIpAddress)).append("\n");
    sb.append("    localLinkId: ").append(toIndentedString(localLinkId)).append("\n");
    sb.append("    dstGwIpAddress: ").append(toIndentedString(dstGwIpAddress)).append("\n");
    sb.append("    remoteLinkId: ").append(toIndentedString(remoteLinkId)).append("\n");
    sb.append("    networkLayer: ").append(toIndentedString(networkLayer)).append("\n");
    sb.append("    interNfviPopNetworkType: ").append(toIndentedString(interNfviPopNetworkType)).append("\n");
    sb.append("    interNfviPopNetworkTopology: ").append(toIndentedString(interNfviPopNetworkTopology)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

