/*
 * MTP Manager API
 * MTP Manager API
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.rl.extinterface.nbi.swagger.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * MECAppDInfoInner
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-08T16:03:30.222Z")
public class MECAppDInfoInner {
  @SerializedName("appDAttributes")
  private MECAppDInfoInnerAppDAttributes appDAttributes = null;

  public MECAppDInfoInner appDAttributes(MECAppDInfoInnerAppDAttributes appDAttributes) {
    this.appDAttributes = appDAttributes;
    return this;
  }

   /**
   * Get appDAttributes
   * @return appDAttributes
  **/
  @ApiModelProperty(required = true, value = "")
  public MECAppDInfoInnerAppDAttributes getAppDAttributes() {
    return appDAttributes;
  }

  public void setAppDAttributes(MECAppDInfoInnerAppDAttributes appDAttributes) {
    this.appDAttributes = appDAttributes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MECAppDInfoInner meCAppDInfoInner = (MECAppDInfoInner) o;
    return Objects.equals(this.appDAttributes, meCAppDInfoInner.appDAttributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appDAttributes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MECAppDInfoInner {\n");
    
    sb.append("    appDAttributes: ").append(toIndentedString(appDAttributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

