/*
 * MTP Manager API
 * MTP Manager API
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.rl.extinterface.nbi.swagger.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Set Request of PNF
 */
@ApiModel(description = "Set Request of PNF")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-08T16:03:30.222Z")
public class PNFRequest {
  @SerializedName("pnfId")
  private String pnfId = null;

  @SerializedName("popId")
  private String popId = null;

  @SerializedName("metaData")
  private MetaData metaData = null;

  public PNFRequest pnfId(String pnfId) {
    this.pnfId = pnfId;
    return this;
  }

   /**
   * Identifier of the resource
   * @return pnfId
  **/
  @ApiModelProperty(value = "Identifier of the resource")
  public String getPnfId() {
    return pnfId;
  }

  public void setPnfId(String pnfId) {
    this.pnfId = pnfId;
  }

  public PNFRequest popId(String popId) {
    this.popId = popId;
    return this;
  }

   /**
   * Identifier of the resource
   * @return popId
  **/
  @ApiModelProperty(value = "Identifier of the resource")
  public String getPopId() {
    return popId;
  }

  public void setPopId(String popId) {
    this.popId = popId;
  }

  public PNFRequest metaData(MetaData metaData) {
    this.metaData = metaData;
    return this;
  }

   /**
   * Get metaData
   * @return metaData
  **/
  @ApiModelProperty(required = true, value = "")
  public MetaData getMetaData() {
    return metaData;
  }

  public void setMetaData(MetaData metaData) {
    this.metaData = metaData;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PNFRequest pnFRequest = (PNFRequest) o;
    return Objects.equals(this.pnfId, pnFRequest.pnfId) &&
        Objects.equals(this.popId, pnFRequest.popId) &&
        Objects.equals(this.metaData, pnFRequest.metaData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pnfId, popId, metaData);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PNFRequest {\n");
    
    sb.append("    pnfId: ").append(toIndentedString(pnfId)).append("\n");
    sb.append("    popId: ").append(toIndentedString(popId)).append("\n");
    sb.append("    metaData: ").append(toIndentedString(metaData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

