/*
 * 5GT-MTP PA API
 * REST-API for the MTP PA. Find more at http://5g-transformer.eu
 *
 * OpenAPI spec version: 0.0.0
 * Contact: cnd@lists.cttc.es
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import com.rl.extinterface.pa.swagger.client.model.CompRouteInput;
import com.rl.extinterface.pa.swagger.client.model.InlineResponse200;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InterNfviPopCompRouteApi
 */
@Ignore
public class InterNfviPopCompRouteApiTest {

    private final InterNfviPopCompRouteApi api = new InterNfviPopCompRouteApi();

    
    /**
     * Computes the interNfviPop connectivity between a pair of PEs with specific network constraints and selects specific servers/hosts within NfviPops
     *
     * Computes the interNfviPop connectivity between a pair of PEs with specific network constraints and selects specific servers/hosts within NfviPops
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void compRouteInterNfviPopTest() throws ApiException {
        String interNfviConnectivityId = null;
        CompRouteInput params = null;
        InlineResponse200 response = api.compRouteInterNfviPop(interNfviConnectivityId, params);

        // TODO: test validations
    }
    
}
