/*
 * MTP Manager API
 * MTP Manager API
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.rl.extinterface.nbi.swagger.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.rl.extinterface.nbi.swagger.model.PNFInfo;
import java.io.IOException;

/**
 * PNFlistInner
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-11-12T12:38:09.537Z")



public class PNFlistInner {
  @SerializedName("pnfinfo")
  private PNFInfo pnfinfo = null;

  public PNFlistInner pnfinfo(PNFInfo pnfinfo) {
    this.pnfinfo = pnfinfo;
    return this;
  }

   /**
   * Get pnfinfo
   * @return pnfinfo
  **/
  @ApiModelProperty(required = true, value = "")
  public PNFInfo getPnfinfo() {
    return pnfinfo;
  }

  public void setPnfinfo(PNFInfo pnfinfo) {
    this.pnfinfo = pnfinfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PNFlistInner pnFlistInner = (PNFlistInner) o;
    return Objects.equals(this.pnfinfo, pnFlistInner.pnfinfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pnfinfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PNFlistInner {\n");
    
    sb.append("    pnfinfo: ").append(toIndentedString(pnfinfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

