/*
 * 5GT-MTP PA API
 * REST-API for the MTP PA. Find more at http://5g-transformer.eu
 *
 * OpenAPI spec version: 0.0.0
 * Contact: cnd@lists.cttc.es
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.rl.extinterface.pa.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * CompRouteOutputInterWanLinks
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-05-02T08:45:54.546Z")
public class CompRouteOutputInterWanLinks {
  @SerializedName("aWimId")
  private String aWimId = null;

  @SerializedName("zWimId")
  private String zWimId = null;

  @SerializedName("aPEId")
  private String aPEId = null;

  @SerializedName("zPEId")
  private String zPEId = null;

  @SerializedName("aLinkId")
  private Integer aLinkId = null;

  @SerializedName("zLinkId")
  private Integer zLinkId = null;

  public CompRouteOutputInterWanLinks aWimId(String aWimId) {
    this.aWimId = aWimId;
    return this;
  }

   /**
   * Identifier of outgoing WIM in the inter-WAN link
   * @return aWimId
  **/
  @ApiModelProperty(required = true, value = "Identifier of outgoing WIM in the inter-WAN link")
  public String getAWimId() {
    return aWimId;
  }

  public void setAWimId(String aWimId) {
    this.aWimId = aWimId;
  }

  public CompRouteOutputInterWanLinks zWimId(String zWimId) {
    this.zWimId = zWimId;
    return this;
  }

   /**
   * Identifier of incoming WIM in the inter-WAN link
   * @return zWimId
  **/
  @ApiModelProperty(required = true, value = "Identifier of incoming WIM in the inter-WAN link")
  public String getZWimId() {
    return zWimId;
  }

  public void setZWimId(String zWimId) {
    this.zWimId = zWimId;
  }

  public CompRouteOutputInterWanLinks aPEId(String aPEId) {
    this.aPEId = aPEId;
    return this;
  }

   /**
   * outgoing PE Id
   * @return aPEId
  **/
  @ApiModelProperty(required = true, value = "outgoing PE Id")
  public String getAPEId() {
    return aPEId;
  }

  public void setAPEId(String aPEId) {
    this.aPEId = aPEId;
  }

  public CompRouteOutputInterWanLinks zPEId(String zPEId) {
    this.zPEId = zPEId;
    return this;
  }

   /**
   * incoming PE Id
   * @return zPEId
  **/
  @ApiModelProperty(required = true, value = "incoming PE Id")
  public String getZPEId() {
    return zPEId;
  }

  public void setZPEId(String zPEId) {
    this.zPEId = zPEId;
  }

  public CompRouteOutputInterWanLinks aLinkId(Integer aLinkId) {
    this.aLinkId = aLinkId;
    return this;
  }

   /**
   * Link Id. attached to the aPEId
   * @return aLinkId
  **/
  @ApiModelProperty(required = true, value = "Link Id. attached to the aPEId")
  public Integer getALinkId() {
    return aLinkId;
  }

  public void setALinkId(Integer aLinkId) {
    this.aLinkId = aLinkId;
  }

  public CompRouteOutputInterWanLinks zLinkId(Integer zLinkId) {
    this.zLinkId = zLinkId;
    return this;
  }

   /**
   * Link Id. attached to the zPEId
   * @return zLinkId
  **/
  @ApiModelProperty(required = true, value = "Link Id. attached to the zPEId")
  public Integer getZLinkId() {
    return zLinkId;
  }

  public void setZLinkId(Integer zLinkId) {
    this.zLinkId = zLinkId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CompRouteOutputInterWanLinks compRouteOutputInterWanLinks = (CompRouteOutputInterWanLinks) o;
    return Objects.equals(this.aWimId, compRouteOutputInterWanLinks.aWimId) &&
        Objects.equals(this.zWimId, compRouteOutputInterWanLinks.zWimId) &&
        Objects.equals(this.aPEId, compRouteOutputInterWanLinks.aPEId) &&
        Objects.equals(this.zPEId, compRouteOutputInterWanLinks.zPEId) &&
        Objects.equals(this.aLinkId, compRouteOutputInterWanLinks.aLinkId) &&
        Objects.equals(this.zLinkId, compRouteOutputInterWanLinks.zLinkId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(aWimId, zWimId, aPEId, zPEId, aLinkId, zLinkId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CompRouteOutputInterWanLinks {\n");
    
    sb.append("    aWimId: ").append(toIndentedString(aWimId)).append("\n");
    sb.append("    zWimId: ").append(toIndentedString(zWimId)).append("\n");
    sb.append("    aPEId: ").append(toIndentedString(aPEId)).append("\n");
    sb.append("    zPEId: ").append(toIndentedString(zPEId)).append("\n");
    sb.append("    aLinkId: ").append(toIndentedString(aLinkId)).append("\n");
    sb.append("    zLinkId: ").append(toIndentedString(zLinkId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

