/*
 * 5GT-MTP PA API
 * REST-API for the MTP PA. Find more at http://5g-transformer.eu
 *
 * OpenAPI spec version: 0.0.0
 * Contact: cnd@lists.cttc.es
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.rl.extinterface.pa.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.rl.extinterface.pa.swagger.client.model.CompRouteOutput;
import java.io.IOException;

/**
 * InlineResponse200
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-05-02T08:45:54.546Z")
public class InlineResponse200 {
  @SerializedName("compRouteOutput")
  private CompRouteOutput compRouteOutput = null;

  public InlineResponse200 compRouteOutput(CompRouteOutput compRouteOutput) {
    this.compRouteOutput = compRouteOutput;
    return this;
  }

   /**
   * Get compRouteOutput
   * @return compRouteOutput
  **/
  @ApiModelProperty(value = "")
  public CompRouteOutput getCompRouteOutput() {
    return compRouteOutput;
  }

  public void setCompRouteOutput(CompRouteOutput compRouteOutput) {
    this.compRouteOutput = compRouteOutput;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse200 inlineResponse200 = (InlineResponse200) o;
    return Objects.equals(this.compRouteOutput, inlineResponse200.compRouteOutput);
  }

  @Override
  public int hashCode() {
    return Objects.hash(compRouteOutput);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse200 {\n");
    
    sb.append("    compRouteOutput: ").append(toIndentedString(compRouteOutput)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

