# coding: utf-8

"""
    5Growth RL RA API

    RESTful API for the 5Gr RL RA. Find more at http://5growth.eu  # noqa: E501

    OpenAPI spec version: 1.1.1
    Contact: cnd@lists.cttc.es
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class CompRouteInputNfviPops(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'vim_id': 'str',
        'nfvi_pop_id': 'str',
        'net_gw_ip_address': 'str',
        'attached_pe_id': 'str',
        'resource_zone_attributes': 'list[CompRouteInputResourceZoneAttributes]'
    }

    attribute_map = {
        'vim_id': 'vimId',
        'nfvi_pop_id': 'nfviPopId',
        'net_gw_ip_address': 'netGwIpAddress',
        'attached_pe_id': 'attachedPeId',
        'resource_zone_attributes': 'resourceZoneAttributes'
    }

    def __init__(self, vim_id=None, nfvi_pop_id=None, net_gw_ip_address=None, attached_pe_id=None, resource_zone_attributes=None):  # noqa: E501
        """CompRouteInputNfviPops - a model defined in Swagger"""  # noqa: E501

        self._vim_id = None
        self._nfvi_pop_id = None
        self._net_gw_ip_address = None
        self._attached_pe_id = None
        self._resource_zone_attributes = None
        self.discriminator = None

        self.vim_id = vim_id
        self.nfvi_pop_id = nfvi_pop_id
        self.net_gw_ip_address = net_gw_ip_address
        self.attached_pe_id = attached_pe_id
        self.resource_zone_attributes = resource_zone_attributes

    @property
    def vim_id(self):
        """Gets the vim_id of this CompRouteInputNfviPops.  # noqa: E501

        Identifier of VIM  # noqa: E501

        :return: The vim_id of this CompRouteInputNfviPops.  # noqa: E501
        :rtype: str
        """
        return self._vim_id

    @vim_id.setter
    def vim_id(self, vim_id):
        """Sets the vim_id of this CompRouteInputNfviPops.

        Identifier of VIM  # noqa: E501

        :param vim_id: The vim_id of this CompRouteInputNfviPops.  # noqa: E501
        :type: str
        """
        if vim_id is None:
            raise ValueError("Invalid value for `vim_id`, must not be `None`")  # noqa: E501

        self._vim_id = vim_id

    @property
    def nfvi_pop_id(self):
        """Gets the nfvi_pop_id of this CompRouteInputNfviPops.  # noqa: E501

        Identifier of Nfvi-Pop  # noqa: E501

        :return: The nfvi_pop_id of this CompRouteInputNfviPops.  # noqa: E501
        :rtype: str
        """
        return self._nfvi_pop_id

    @nfvi_pop_id.setter
    def nfvi_pop_id(self, nfvi_pop_id):
        """Sets the nfvi_pop_id of this CompRouteInputNfviPops.

        Identifier of Nfvi-Pop  # noqa: E501

        :param nfvi_pop_id: The nfvi_pop_id of this CompRouteInputNfviPops.  # noqa: E501
        :type: str
        """
        if nfvi_pop_id is None:
            raise ValueError("Invalid value for `nfvi_pop_id`, must not be `None`")  # noqa: E501

        self._nfvi_pop_id = nfvi_pop_id

    @property
    def net_gw_ip_address(self):
        """Gets the net_gw_ip_address of this CompRouteInputNfviPops.  # noqa: E501

        Nfvi-Pop Gw IP Address  # noqa: E501

        :return: The net_gw_ip_address of this CompRouteInputNfviPops.  # noqa: E501
        :rtype: str
        """
        return self._net_gw_ip_address

    @net_gw_ip_address.setter
    def net_gw_ip_address(self, net_gw_ip_address):
        """Sets the net_gw_ip_address of this CompRouteInputNfviPops.

        Nfvi-Pop Gw IP Address  # noqa: E501

        :param net_gw_ip_address: The net_gw_ip_address of this CompRouteInputNfviPops.  # noqa: E501
        :type: str
        """
        if net_gw_ip_address is None:
            raise ValueError("Invalid value for `net_gw_ip_address`, must not be `None`")  # noqa: E501

        self._net_gw_ip_address = net_gw_ip_address

    @property
    def attached_pe_id(self):
        """Gets the attached_pe_id of this CompRouteInputNfviPops.  # noqa: E501

        WAN PE Id attached to the Nfvi-Pop Gw  # noqa: E501

        :return: The attached_pe_id of this CompRouteInputNfviPops.  # noqa: E501
        :rtype: str
        """
        return self._attached_pe_id

    @attached_pe_id.setter
    def attached_pe_id(self, attached_pe_id):
        """Sets the attached_pe_id of this CompRouteInputNfviPops.

        WAN PE Id attached to the Nfvi-Pop Gw  # noqa: E501

        :param attached_pe_id: The attached_pe_id of this CompRouteInputNfviPops.  # noqa: E501
        :type: str
        """
        if attached_pe_id is None:
            raise ValueError("Invalid value for `attached_pe_id`, must not be `None`")  # noqa: E501

        self._attached_pe_id = attached_pe_id

    @property
    def resource_zone_attributes(self):
        """Gets the resource_zone_attributes of this CompRouteInputNfviPops.  # noqa: E501


        :return: The resource_zone_attributes of this CompRouteInputNfviPops.  # noqa: E501
        :rtype: list[CompRouteInputResourceZoneAttributes]
        """
        return self._resource_zone_attributes

    @resource_zone_attributes.setter
    def resource_zone_attributes(self, resource_zone_attributes):
        """Sets the resource_zone_attributes of this CompRouteInputNfviPops.


        :param resource_zone_attributes: The resource_zone_attributes of this CompRouteInputNfviPops.  # noqa: E501
        :type: list[CompRouteInputResourceZoneAttributes]
        """
        if resource_zone_attributes is None:
            raise ValueError("Invalid value for `resource_zone_attributes`, must not be `None`")  # noqa: E501

        self._resource_zone_attributes = resource_zone_attributes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CompRouteInputNfviPops, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CompRouteInputNfviPops):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
