FROM ubuntu:16.04

RUN apt-get update 
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install openjdk-8-jdk
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install netcat

RUN mkdir -p /usr/src/app
COPY . /usr/src/app
WORKDIR /usr/src/app/xml_domain

# JAVA env vars
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64
ENV PATH $JAVA_HOME/bin:$PATH

EXPOSE 50000

#for debug purpose
#CMD ["./wait-for", "evedatabase:3306", "-t", "200000"]

CMD ["./wait-for", "evedatabase:3306", "-t", "90", "--", "java", "-jar", "../target/rl-1.0.jar", "domainlist.xml", "rlapp", "50000"]

